"""Evidence and provenance objects for MedFindr v1.2."""
from __future__ import annotations
from dataclasses import dataclass,field
from typing import Any
@dataclass
class EvidenceItem:
    title:str
    evidence_type:str
    source:str
    source_url:str=""
    claim:str=""
    provenance:str=""
    metadata:dict[str,Any]=field(default_factory=dict)
    @property
    def retrieved_at_utc(self)->str: return str(self.metadata.get("retrieved_at_utc",""))
    def to_dict(self)->dict[str,Any]:
        return {"title":self.title,"evidence_type":self.evidence_type,"source":self.source,
                "source_url":self.source_url,"claim":self.claim,"provenance":self.provenance,
                "metadata":dict(self.metadata)}
def rule_evidence(title:str,claim:str,rule_name:str)->EvidenceItem:
    return EvidenceItem(title,"prototype_rule","MedFindr rule engine",claim=claim,
                        provenance=f"Generated by configured prototype rule: {rule_name}")
def retrieved_evidence(result:dict[str,Any])->EvidenceItem:
    return EvidenceItem("Retrieved drug-label information","regulatory_label",
        str(result.get("source","Unknown source")),str(result.get("source_url","")),
        "Retrieved label fields are displayed separately from MedFindr-generated analysis.",
        "External retrieval; inspect source metadata before reuse.",
        {"query":result.get("query",""),"retrieved_at_utc":result.get("retrieved_at_utc","")})
