"""
Structured Response Engine
Version: 07.5

Responsible for generating a complete, consistent, typed response object.
All section logic lives here so the UI remains thin and future features
(EBM, tools, dual-view, etc.) can be added cleanly.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from utils.urgency import UrgencyResult, assess_urgency
from utils.drug_lookup import search_drug


@dataclass
class Section:
    title: str
    content: str
    level: Optional[str] = None          # used for urgency visual level
    items: List[str] = field(default_factory=list)


@dataclass
class StructuredResponse:
    concern: str
    urgency: UrgencyResult
    sections: List[Section] = field(default_factory=list)
    drug_result: Optional[Dict[str, Any]] = None
    notes: str = ""

    def to_dict(self) -> dict:
        return {
            "concern": self.concern,
            "urgency": self.urgency.to_dict(),
            "sections": [
                {
                    "title": s.title,
                    "content": s.content,
                    "level": s.level,
                    "items": s.items,
                }
                for s in self.sections
            ],
            "drug_result": self.drug_result,
            "notes": self.notes,
        }


def build_response(
    concern: str,
    drug_name: Optional[str] = None,
) -> StructuredResponse:
    """
    Main entry point for the response engine.
    Produces a complete StructuredResponse from raw user input.
    """
    cleaned_concern = (concern or "").strip()

    # 1. Urgency assessment
    urgency = assess_urgency(cleaned_concern)

    # 2. Build core sections
    sections: List[Section] = []

    # Section 1 – Understanding
    sections.append(
        Section(
            title="1. Understanding the Concern",
            content=cleaned_concern if cleaned_concern else "No concern provided.",
        )
    )

    # Section 2 – Urgency (detailed content lives in urgency object)
    sections.append(
        Section(
            title="2. Urgency Assessment",
            content=urgency.recommendation,
            level=urgency.level,
            items=urgency.reasons,
        )
    )

    # Section 3 – Next steps (general, safe defaults)
    next_steps_items = [
        "Rest and maintain good hydration",
        "Monitor symptoms over the next 24–48 hours",
        "For mild symptoms, consider seeking pharmacy advice on suitable over-the-counter options",
        "Seek medical attention if symptoms persist, worsen, or new concerning signs appear",
    ]

    # Adjust tone slightly based on urgency
    if urgency.level == "high":
        next_steps_content = (
            "High urgency signals were detected. "
            "Priority should be given to urgent medical evaluation."
        )
    elif urgency.level == "moderate":
        next_steps_content = (
            "Moderate concern indicators are present. "
            "Close monitoring and timely medical review are recommended."
        )
    else:
        next_steps_content = (
            "No strong red-flag patterns detected on the current description. "
            "General self-care measures may be appropriate while monitoring."
        )

    sections.append(
        Section(
            title="3. Possible Next Steps / Remedies (general)",
            content=next_steps_content,
            items=next_steps_items,
        )
    )

    # 3. Optional drug lookup
    drug_result = None
    if drug_name and drug_name.strip():
        drug_result = search_drug(drug_name.strip())

    # 4. Notes
    notes = (
        "This structured response was generated by the MedFindr response engine (v07.5). "
        "Urgency assessment is currently rule-based and fully transparent. "
        "Future versions will incorporate explainable machine learning models "
        "while preserving the same clear output structure."
    )

    return StructuredResponse(
        concern=cleaned_concern,
        urgency=urgency,
        sections=sections,
        drug_result=drug_result,
        notes=notes,
    )
