"""
Structured Response Engine
Version: 07.5 (refined)

Single source of truth for generating a complete, consistent,
typed response object. UI only renders the result.
Designed to stay stable when EBM, tools, or dual-view are added later.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from utils.drug_lookup import search_drug
from utils.urgency import UrgencyResult, assess_urgency


@dataclass
class Section:
    """One display section in the final response."""
    title: str
    content: str
    level: Optional[str] = None          # "high" | "moderate" | "low" | None
    items: List[str] = field(default_factory=list)


@dataclass
class StructuredResponse:
    """Complete structured output produced by the engine."""
    concern: str
    urgency: UrgencyResult
    sections: List[Section] = field(default_factory=list)
    drug_result: Optional[Dict[str, Any]] = None
    notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "concern": self.concern,
            "urgency": self.urgency.to_dict(),
            "sections": [
                {
                    "title": s.title,
                    "content": s.content,
                    "level": s.level,
                    "items": s.items,
                }
                for s in self.sections
            ],
            "drug_result": self.drug_result,
            "notes": self.notes,
        }


def build_response(
    concern: str,
    drug_name: Optional[str] = None,
) -> StructuredResponse:
    """
    Build a complete StructuredResponse from raw user input.

    This is the only public entry point the UI should call.
    """
    cleaned = (concern or "").strip()

    # --- Urgency ---
    urgency: UrgencyResult = assess_urgency(cleaned)

    sections: List[Section] = []

    # 1. Understanding
    sections.append(
        Section(
            title="1. Understanding the Concern",
            content=cleaned if cleaned else "No concern text provided.",
        )
    )

    # 2. Urgency Assessment
    sections.append(
        Section(
            title="2. Urgency Assessment",
            content=urgency.recommendation,
            level=urgency.level,
            items=list(urgency.reasons),
        )
    )

    # 3. Next Steps (tone adapts lightly to urgency)
    if urgency.level == "high":
        next_content = (
            "High urgency signals were detected. "
            "Urgent medical evaluation should be prioritised."
        )
    elif urgency.level == "moderate":
        next_content = (
            "Moderate concern indicators are present. "
            "Close monitoring and timely medical review are recommended."
        )
    else:
        next_content = (
            "No strong red-flag patterns detected on the current description. "
            "General self-care measures may be appropriate while continuing to monitor."
        )

    next_items = [
        "Rest and maintain good hydration",
        "Monitor symptoms over the next 24–48 hours",
        "For mild symptoms, consider seeking pharmacy advice on suitable over-the-counter options",
        "Seek medical attention if symptoms persist, worsen, or new concerning signs appear",
    ]

    sections.append(
        Section(
            title="3. Possible Next Steps / Remedies (general)",
            content=next_content,
            items=next_items,
        )
    )

    # Optional drug lookup
    drug_result: Optional[Dict[str, Any]] = None
    if drug_name and drug_name.strip():
        drug_result = search_drug(drug_name.strip())

    notes = (
        "Structured response generated by MedFindr response engine (v07.5). "
        "Urgency assessment is currently rule-based and fully transparent. "
        "Future versions will add explainable machine-learning models "
        "while preserving this clear output structure."
    )

    return StructuredResponse(
        concern=cleaned,
        urgency=urgency,
        sections=sections,
        drug_result=drug_result,
        notes=notes,
    )
