"""
Structured Response Engine
Version: 08.1 Beta testing EBM

Now optionally includes EBM-style risk explanation.
Remains fully backward compatible.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from utils.drug_lookup import search_drug
from utils.ebm_risk import EBMExplanation, assess_risk_ebm
from utils.urgency import UrgencyResult, assess_urgency


@dataclass
class Section:
    title: str
    content: str
    level: Optional[str] = None
    items: List[str] = field(default_factory=list)


@dataclass
class StructuredResponse:
    concern: str
    urgency: UrgencyResult
    ebm: Optional[EBMExplanation] = None
    sections: List[Section] = field(default_factory=list)
    drug_result: Optional[Dict[str, Any]] = None
    notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "concern": self.concern,
            "urgency": self.urgency.to_dict(),
            "ebm": self.ebm.to_dict() if self.ebm else None,
            "sections": [
                {
                    "title": s.title,
                    "content": s.content,
                    "level": s.level,
                    "items": s.items,
                }
                for s in self.sections
            ],
            "drug_result": self.drug_result,
            "notes": self.notes,
        }


def build_response(
    concern: str,
    drug_name: Optional[str] = None,
    include_ebm: bool = True,
) -> StructuredResponse:
    """
    Build a complete StructuredResponse.
    """
    cleaned = (concern or "").strip()

    # 1. Rule-based urgency (always on)
    urgency: UrgencyResult = assess_urgency(cleaned)

    # 2. Optional EBM-style risk layer
    ebm_result: Optional[EBMExplanation] = None
    if include_ebm:
        ebm_result = assess_risk_ebm(cleaned, urgency_level=urgency.level)

    sections: List[Section] = []

    # Section 1
    sections.append(
        Section(
            title="1. Understanding the Concern",
            content=cleaned if cleaned else "No concern text provided.",
        )
    )

    # Section 2 – Urgency
    sections.append(
        Section(
            title="2. Urgency Assessment (Rule-based)",
            content=urgency.recommendation,
            level=urgency.level,
            items=list(urgency.reasons),
        )
    )

    # Section 3 – EBM Risk (if available)
    if ebm_result:
        ebm_items = [f"{k}: {v:.2f}" for k, v in ebm_result.local_contribution.items()]
        sections.append(
            Section(
                title="3. Explainable Risk Assessment (EBM Beta)",
                content=ebm_result.summary,
                level=ebm_result.risk_level,
                items=ebm_result.top_factors + ebm_items,
            )
        )

    # Section 4 – Next Steps
    if urgency.level == "high":
        next_content = "High urgency signals detected. Urgent medical evaluation should be prioritised."
    elif urgency.level == "moderate":
        next_content = "Moderate concern indicators present. Close monitoring and timely medical review are recommended."
    else:
        next_content = "No strong red-flag patterns detected. General self-care measures may be appropriate while monitoring."

    next_items = [
        "Rest and maintain good hydration",
        "Monitor symptoms over the next 24–48 hours",
        "For mild symptoms, consider seeking pharmacy advice on suitable over-the-counter options",
        "Seek medical attention if symptoms persist, worsen, or new concerning signs appear",
    ]

    sections.append(
        Section(
            title="4. Possible Next Steps / Remedies (general)",
            content=next_content,
            items=next_items,
        )
    )

    # Optional drug
    drug_result = None
    if drug_name and drug_name.strip():
        drug_result = search_drug(drug_name.strip())

    notes = (
        "Response generated by MedFindr v08.1 (Beta testing EBM). "
        "Urgency is rule-based and fully transparent. "
        "EBM component is currently a structured beta placeholder – "
        "a trained InterpretML model will be integrated in the next iteration."
    )

    return StructuredResponse(
        concern=cleaned,
        urgency=urgency,
        ebm=ebm_result,
        sections=sections,
        drug_result=drug_result,
        notes=notes,
    )
